#Database Settings
Redis:
  Hostname: 127.0.0.1
  Port: 6379
  Password: ""
  AcceptedTeleportsKey: "casestudy#accepted_teleports"

MongoDB:
  Hostname: 127.0.0.1
  Port: 27017
  Username: ""
  Password: ""
  Database: "casestudy"
  TeleportHistoryCollection: "teleporthistory"