name: CaseStudy
version: '${project.version}'
main: io.github.furkanaliunal.casestudy.bukkit.CaseStudy
api-version: 1.13
depend: [ JedisDependency ]
authors: [ Onwexrys ]
description: Multiserver TPA request. It's an example project to show my skills on many things
website: https://github.com/furkanaliunal